---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: deprovision-finalizer-sa
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    argocd.argoproj.io/sync-wave: "0"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deprovision-finalizer-role
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    argocd.argoproj.io/sync-wave: "0"
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deprovision-finalizer-binding
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    argocd.argoproj.io/sync-wave: "0"
subjects:
  - kind: ServiceAccount
    name: deprovision-finalizer-sa
roleRef:
  kind: Role
  name: deprovision-finalizer-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: Job
metadata:
  name: add-deprovision-finalizers
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    argocd.argoproj.io/sync-wave: "1"
spec:
  activeDeadlineSeconds: 3600
  backoffLimit: 2
  template:
    spec:
      serviceAccountName: deprovision-finalizer-sa
      restartPolicy: Never
      imagePullSecrets:
        - name: pull-secret
      containers:
        - name: add-finalizers
          image: registry.redhat.io/openshift4/ose-cli:v4.14
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: FINALIZER
              value: "openshiftpartnerlabs.com/deprovision"
            - name: DEPROVISION_LABEL
              value: "openshiftpartnerlabs.com/deprovision-pending"
          command:
            - /bin/bash
            - -c
            - |
              set -e

              CLUSTER_NAME="$NAMESPACE"
              METADATA_SECRET="${CLUSTER_NAME}-metadata-json"
              SECRETS=("aws-credentials" "${CLUSTER_NAME}-metadata-json")
              POLL_INTERVAL=30
              MAX_WAIT=3600

              echo "=== Adding deprovision finalizers ==="
              echo "Namespace: $NAMESPACE"
              echo "Cluster: $CLUSTER_NAME"
              echo ""

              # Wait for metadata-json secret to exist
              echo "Waiting for $METADATA_SECRET to exist..."
              ELAPSED=0
              while [ $ELAPSED -lt $MAX_WAIT ]; do
                if oc get secret "$METADATA_SECRET" -n "$NAMESPACE" &>/dev/null; then
                  echo "Secret $METADATA_SECRET found!"
                  break
                fi
                echo "  Still waiting... ($ELAPSED seconds elapsed)"
                sleep $POLL_INTERVAL
                ELAPSED=$((ELAPSED + POLL_INTERVAL))
              done

              if [ $ELAPSED -ge $MAX_WAIT ]; then
                echo "ERROR: Timeout waiting for $METADATA_SECRET"
                exit 1
              fi

              # Add finalizers to both secrets
              for secret in "${SECRETS[@]}"; do
                echo "Processing secret: $secret"

                existing=$(oc get secret "$secret" -n "$NAMESPACE" \
                  -o jsonpath='{.metadata.finalizers}' 2>/dev/null || echo "")

                if [[ "$existing" == *"$FINALIZER"* ]]; then
                  echo "  Finalizer already exists, skipping"
                  continue
                fi

                echo "  Adding finalizer..."
                if [[ -z "$existing" || "$existing" == "null" ]]; then
                  oc patch secret "$secret" -n "$NAMESPACE" --type=json \
                    -p="[{\"op\": \"add\", \"path\": \"/metadata/finalizers\", \"value\": [\"$FINALIZER\"]}]"
                else
                  oc patch secret "$secret" -n "$NAMESPACE" --type=json \
                    -p="[{\"op\": \"add\", \"path\": \"/metadata/finalizers/-\", \"value\": \"$FINALIZER\"}]"
                fi

                echo "  Adding tracking label..."
                oc label secret "$secret" -n "$NAMESPACE" \
                  "$DEPROVISION_LABEL=true" --overwrite

                echo "  Done"
              done

              echo ""
              echo "=== Finalizer setup complete ==="